services:
 facefusion-cpu:
  build:
   context: .
   dockerfile: Dockerfile.cpu
  command: [ 'python', 'facefusion.py', 'run' ]
  volumes:
  - .assets:/facefusion/.assets
  - .caches:/facefusion/.caches
  - .jobs:/facefusion/.jobs
  - ./facefusion/content_analyser.py:/facefusion/facefusion/content_analyser.py
  ports:
  - 7865:7860
